// <auto-generated />
namespace NicaWallet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeaccounticonaddtoAccounttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeaccounticonaddtoAccounttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201709030950231_remove-account-icon-add-to-Account-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
