// <auto-generated />
namespace NicaWallet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCategroyicon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCategroyicon));
        
        string IMigrationMetadata.Id
        {
            get { return "201709021936048_add-Categroy-icon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
