// <auto-generated />
namespace NicaWallet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populateaccountypeandcurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateaccountypeandcurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "201709022046373_populate-accountype-and-currency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
